backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "all"
    label: "All Sites"
    folder: "content"
    create: true
    identifier_field: url
    fields:
      - { label: "Name", name: "name", widget: "string", required: false }
      - { label: "URL", name: "url", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "Thumbnail",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
