backend:
  name: test-repo
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "all"
    label: "All Sites"
    folder: "content/sites"
    create: true
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      # - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      # - { label: "Description", name: "description", widget: "string" }
