backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
# backend:
#   name: test-repo
#   branch: master
# media_folder: public/img
# public_folder: img
# collections:
#   - name: "all"
#     label: "All Sites"
#     folder: "content/sites"
#     create: true
#     identifier_field: name
#     fields:
#       - { label: "Name", name: "name", widget: "string" }
#       - { label: "URL", name: "url", widget: "string" }
#       # - { label: "Thumbnail", name: "thumbnail", widget: "image" }
#       # - { label: "Description", name: "description", widget: "string" }
